on:
  push:
    branches:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to ghcr
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/deve_backend:latest .

      - name: Push on ghcr
        run: |
          docker push ghcr.io/${{ github.repository }}/deve_backend:latest
